model:
  name: 'distilgpt2'
  max_length: 128

dataset:
  name: 'imdb'
  split: 'train[:10%]'
  train_ratio: 0.8

training:
  output_dir: './results'
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  num_train_epochs: 20
  model_path: './results/fine_tuned_model'

generation:
  max_length: 50